name: Validate Terraform

on: 
  workflow_call:
    inputs:
        path:
          description: Path to the terraform configuration
          required: false
          type: string
          default: .
        terraform-version:
          description: Version of terraform
          required: false
          type: string
          default: 1.4.2
        artifact-name:
          type: string
          default: ""
jobs:
  validate:
    name: Perform validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terragrunt Initialise
      working-directory: ${{ inputs.path }}
      run: |
        terraform init --backend=false

    - name: Check formatting of Terraform files
      uses: dflook/terraform-fmt-check@v1

    - name: Run linting rules against Terraform files
      uses: devops-infra/action-tflint@v0.3

    - name: Run terraform validate
      uses: dflook/terraform-validate@v1
      with:
        path: ${{ inputs.path }}

    # - name: Terraform Init
    #   run: |
    #        terraform init --backend=false

    # - name: Terraform Format
    #   run: |
    #         terraform fmt
        
    # - name: Terraform Validate
    #   run: |
    #        terraform validate
